export:
  name: Export
  description: Export history data of any sensor
  fields:
    entity_id:
      name: Entity
      description: "Any entity"
      required: true
      selector:
        entity:
    start:
      name: Start
      description: "Beginning of the interval"
      required: false
      selector:
        datetime:
    end:
      name: End
      description: "Ending of the interval"
      required: false
      selector:
        datetime:
export_device_tracker:
  name: Device tracker export
  description: Export device tracker data in KML format
  fields:
    entity_id:
      name: Entity
      description: "Device tracker entity"
      required: true
      selector:
        entity:
          domain: device_tracker
    start:
      name: Start
      description: "Beginning of the interval"
      required: false
      selector:
        datetime:
    end:
      name: End
      description: "Ending of the interval"
      required: false
      selector:
        datetime:
    max_gap:
      name: Max gap [s]
      description: A period which is not counted as an break
      required: true
      default: 300
      selector:
        number:
          min: 0
          max: 3600
    min_radius:
      name: Min radius [m]
      description: A radius in which a group of coords will not be considered as valid path
      required: true
      default: 100
      selector:
        number:
          min: 0
          max: 1000
    attributes:
      name: Attributes
      description: Additional attributes to include
      required: false
      example: timestamp distance length course speed
      selector:
        text:
    directory:
      name: Directory
      description: Directory part of save location of the tracking data
      required: false
      example: www/history/
      selector:
        text:
    filename:
      name: File name
      description: File name part of save location of the tracking data
      required: false
      example: device_tracker
      selector:
        text: